### ISSUE TITLE
Doc comment specification

### ISSUE THREAD

**Issue by SPGoding** [SPGoding/datapack-language-server#1]
Please refer to https://github.com/Arcensoth/imp-spec/blob/master/docs/imp_doc.md.

# OUTDATED DESCRIPTION

Doc comments are a way to describe a function or a user-defined value for both human and DHP.

There are two types of doc comments: the one for **function** and the one for **user-defined stuff**.

The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED",  "MAY", and "OPTIONAL" in this document are to be interpreted as described in [RFC 2119](https://tools.ietf.org/rfc/rfc2119.txt).

# Function Doc Comments
Function doc comments MUST be put at the very beginning of a function file.

A doc comment MUST begin with `#>` instead of `#`. You MAY put several spaces (` `) or tabs (`\t`) before or after the beginning symbol. You SHOULD put the function's namespaced ID after this symbol. This ID can be used to perform rename operations, show call hierarchy, and many other features provided by DHP.

It's RECOMMENDED to put other comments after this line to describe the function, usage, and any other related stuff of this function, beginning with `#`. You MAY put several _white spaces_ (` `, `\t`, `\r`, `\n`, or `\r\n`) before or after these symbols too. Any lines that are not beginning with `#` (e.g. an empty line, a command, etc.) or are define comments (`#define <type> <id>`) will break the doc comments at that position.

You MAY use annotations which start with `@` to help describe your function, showed below.

Here is an example of a function doc comment.

```mcfunction
#> minecraft:foo
# This function is used to balabala.
# Balabala.
# Balabala.
# @author SPGoding
# @input score #foo params <description of #foo parameter>
# @input
#     score #bar params
#     <description of #bar parameter>

# But don't break the streak of `#`s. For instance, there is an empty line before this line, so this line will not be considered as part of the doc comment.
```

## Annotations

Here's a full list of annotations that you can use within your function doc comment. All parameters in the annotation should be seperated with at least one white space. `...` indicates that this argument will _eat all the characters_ until the end of this doc comment or encounters another annotation.

| Type | Syntax | Description |
| - | - | - |
| author | `@author <string...>` | The author of this function. |
| context | `@context <string...>` | The execution context of this function. |
| deprecated | `@deprecated [<reason...>]` | This function is deprecated. This annotation affects the semantic coloring token modifier for this namespaced ID. |
| handles | `@handles <namespaced_id> [<namespaced_id>, ...]` | Marks this function as an event handler. |
| override | `@override` | Indicates that this function overrides a function intentionally. If `noImplicitOverride` is set to `true` in the config (defaults to `false`), unmarked override will trigger a warning. |
| patch | `@patch` | The same as `@override`. |
| input | `@input data (block\|entity\|storage) <id> <path> [<description...>]` | Defines an NBT data input of this function. ~~The `<id>` part will be treated as a private declaration automatically, and will be used to provide completions in this function file.~~ (Still WIP. See #319 for access modifier proposal.) |
| input | `@input score <score_holder> <objective> [<description...>]` | Defines a score input of this function. ~~The `<score_holder>` part will be treated as a private declaration automatically, and will be used to provide completions in this function file.~~ (Still WIP. See #319 for access modifier proposal.) |
| output | `@output data (block\|entity\|storage) <id> <path> [<description...>]` | Defines an NBT data output of this function. ~~The `<id>` part will be treated as a private declaration automatically, and will be used to provide completions in this function file.~~ (Still WIP. See #319 for access modifier proposal.) |
| output | `@output score <score_holder> <objective> [<description...>]` | Defines a score output of this function. ~~The `<score_holder>` part will be treated as a private declaration automatically, and will be used to provide completions in this function file.~~ (Still WIP. See #319 for access modifier proposal.) |
| private | `@private` | WIP. See #319 for access modifier proposal. |
| within | `@within <namespaced_id> [<namespaced_id>, ...]` | WIP. See #319 for access modifier proposal. |
| internal | `@internal` | WIP. See #319 for access modifier proposal. |
| public | `@public` | WIP. See #319 for access modifier proposal. |
| _custom_ | `@<custom_annotation_name> [<parameters...>]` | Custom annotations. |

# Other Doc Comments

Doc comments for other user-defined stuff are similar to function doc comment, but with these differences:
- You SHOULD NOT write anything other than white spaces after the beginning `#>` symbol.
- Only `author`, `deprecated`, `private`, `within`, `internal`, `public`, and custom annotations work.

The doc comment MUST be write right before the corresponding stuff. Here are several working examples:

```mcfunction
#> 
# Balalala.
# @internal
scoreboard objectives add test dummy

#> 
# Alalalab.
# @deprecated
# @within spgoding:
#define entity SPGoding
```

------
Reference: [Arcensoth](https://github.com/Arcensoth)'s [IMP Function Documentation Format](https://github.com/Arcensoth/datapacks/blob/master/impdoc.md).

**Comment by Arcensoth** [comment]
I have a habit of using annotations like these in larger, complex packs, and an IDE feature to support them directly would be unreal. (I even considered this for language-mcfunction [block comments](https://github.com/Arcensoth/language-mcfunction#custom-block-comments) but decided it was too complex for the extension's scope.) I decided to write it all down somewhere to help formalize it:

<https://github.com/Arcensoth/datapacks/blob/master/impdoc.md>

It hasn't been updated to 1.15 yet (`storage`) and the format is a bit different from yours, but maybe it can give you some ideas.

**Comment by SPGoding** [comment]
What IDE supports can be provided regard these document comments?

The only two things I could come up with are completions and hover information.

**Comment by Arcensoth** [comment]
Yeah, hover information would be a huge plus. Completions could also be useful but I can't think of how the user would initiate them.

Here's another one for arguments specifically. Perhaps a warning over the function call if you have not defined the required arguments in the current scope. A bit verbose, maybe, but I'd argue that anyone who wants to use this type of feature has likely already committed to this level of verbosity. In case an argument is defined outside the current scope (for example by another function), it would be useful to have a special type of comment that notifies the language server that the argument is known to be defined elsewhere.

**Comment by SPGoding** [comment]
I'm planning to add four access modifiers: `public`, `internal`, `within`, and `private`. These modifiers only affect the completions and the strict checks (if enabled in the config) provided by DHP. They all exist in form of comments, so they will be simply ignored by Minecraft.

- `public` means this stuff can be accessed anywhere, which is the behavior of the game. The default modifier will be `public`, so _users who don't want this verbose feature won't be bothered by it_. Public stuff will be provided in the completions list in the whole workspace.
- `internal` means this stuff can only be accessed in the same datapack. If a workspace only has one root folder, then `internal` will work as the same as `public` in this workspace.
- `within` means this stuff can only be accessed from a set of functions.
- `private` means this stuff can only be accessed in the same mcfunction file. Though I don't think any functions could have this modifier (a function with `@private` and `@user`annotation which recursive itself?), it's useful in `#define` comments. See below for more information.

These modifiers (besides `within` because it's too complex for me to implement it in`#define` comments) can not only be used in function documentation annotations, but also in `#define` comments by writing `#define-<modifier>`. `#define` will become a shortcut of `#define-public` so that existing comments won't break.

BTW, entity names in `@args` and `@returns` annotation will be automatically treated as a `#define-private entity` declaration.

Any ideas?
