### ISSUE TITLE
Faild to parse `execute (rotated as|positioned as|facing entity)`

### ISSUE THREAD

**Issue by MinecraftPeace** [SPGoding/datapack-language-server#100]
![● add mcfunction -  1 14+ 多重锁定式追踪导弹v4 0 0 - Visual Studio Code 2019_11_9 11_07_51](https://user-images.githubusercontent.com/57551211/68521980-406cf100-02e1-11ea-8a92-52c4e0974d36.png)

**Comment by MinecraftPeace** [comment]
ps：貌似facing entity的时候也会标错

**Comment by SPGoding** [comment]
@all-contributors add MinecraftPeace for bug

**Comment by SPGoding** [comment]
@all-contributors add MinecraftPeace for bug
