### ISSUE TITLE
"scoreboard players reset" selector should allow almost all characters

### ISSUE THREAD

**Issue by ChenCMD** [SPGoding/datapack-language-server#128]
An error occurs when a character such as # $ % etc... is written in [selector] of `scoreboard players reset [selector]`

**Comment by ChenCMD** [comment]
![image](https://user-images.githubusercontent.com/46134240/68745482-1d707300-063a-11ea-8265-c022e3eba9ad.png)

**Comment by SPGoding** [comment]
@all-contributors

Add ChenCMD for bug.
