### ISSUE TITLE
NBT described in the Pose tag of armor_stand is not a compound tag but a List tag.

### ISSUE THREAD

**Issue by ChenCMD** [SPGoding/datapack-language-server#133]
Example:`{Pose:{Head:[0f,0f,0f]}}`

**Comment by ChenCMD** [comment]
![image](https://user-images.githubusercontent.com/46134240/68828976-c1b1f280-06ea-11ea-9013-6825bbb5f6a6.png)

![image](https://user-images.githubusercontent.com/46134240/68828938-a515ba80-06ea-11ea-9af9-e3f1051ebe0a.png)
It hasn't been fixed :(
The error is the same.

**Comment by ChenCMD** [comment]
This bug is not fixed, the error is the same

**Comment by SPGoding** [comment]
Looks like the dependency is not updated correctly.
