### ISSUE TITLE
Teleport does not recognize the third and subsequent arguments.

### ISSUE THREAD

**Issue by ChenCMD** [SPGoding/datapack-language-server#141]
An error occurred when I wrote a command like
![image](https://user-images.githubusercontent.com/46134240/68829601-929c8080-06ec-11ea-86bd-3e4d6206daa7.png)

**Comment by ChenCMD** [comment]
I'm sorry. This may have been the problem

**Comment by SPGoding** [comment]
I thought I had fixed this, but actually not. :joy:
