### ISSUE TITLE
An error occurred that caused the extension to stop working

### ISSUE THREAD

**Issue by ChenCMD** [SPGoding/datapack-language-server#142]
The error that occurred is the following error:
**Request initialize failed with message: ENOENT: no such file or directory, open
'c:\Users\[Omitted]\datapacks\SkillFor\data\minecraft\loot_tables\blocks\crafting_table.json'**

**Comment by ChenCMD** [comment]
![image](https://user-images.githubusercontent.com/46134240/68831831-bb277900-06f2-11ea-982c-5053f3632fa2.png)

**Comment by SPGoding** [comment]
I'm not sure whether this is fixed. You can try it out when the next version (hopefully v1.8.1) released later today.
