### ISSUE TITLE
A warning occurs when browsing the vanilla LootTable.

### ISSUE THREAD

**Issue by ChenCMD** [SPGoding/datapack-language-server#148]
If you refer to a Loottable of a block that is not described in the Datapack, you will be warned
![image](https://user-images.githubusercontent.com/46134240/68862257-7b7f8200-0730-11ea-82c0-d04070da8cb3.png)

**Comment by SPGoding** [comment]
Because the loot table doesn't exist in your workspace. I think I should disable the warning by default and provide an option to enable it in the future.
