### ISSUE TITLE
id: "itemid" should output a warning

### ISSUE THREAD

**Issue by ChenCMD** [SPGoding/datapack-language-server#169]
Example:
`id:"stone"` ×
`id:"minecraft:stone"` 〇
Now, no warning is output even in the previous example sentence.
In addition, character completion should be corrected accordingly.

**Comment by SPGoding** [comment]
Though it's ok to write  `stone` without `minecraft:` prefix in some cases. I will treat those cases separately.

**Comment by SPGoding** [comment]
![image](https://user-images.githubusercontent.com/15277496/69606817-78667a80-0fe9-11ea-9325-edc74f1ee0dd.png)
Finally! Though there are still a lot of things to do before the next version is released
