### ISSUE TITLE
Syntax conflicts between 1.12 mcfunction and 1.13 mcfunction

### ISSUE THREAD

**Issue by tremblestarman** [SPGoding/datapack-language-server#173]
I've got to develop a cross-version project using different syntaxes in 1.12 and 1.13. It works well in 1.13, but when I opened mcfunction documents applicable for 1.12, something happened like this:

![](https://i.loli.net/2019/11/19/KzBIWT5Nn1Xkbf8.png "the annoying red underline")

While using datapack-helper, it works as expected:

![](https://i.loli.net/2019/11/19/hEtJo7YjPAIzQyp.png "well")

I'm not here to force you to develop another version to support 1.12, but at least try to identify if a mcfunction focuses on 1.12 instead of 1.13 (like all syntaxes of commands are available in 1.12 or more simply, are not available in 1.13), and do not do the deed on it.

**Comment by SPGoding** [comment]
Is it an acceptable workaround to add a comment like `#datapack-helper-plus:ignore` at the beginning of the file?

**Comment by tremblestarman** [comment]
that's not as intelligent as I had expected and doesn't really free my hand as I have over hundreds of scripts to IGNORE

**Comment by tremblestarman** [comment]
that's not as intelligent as I had expected and doesn't really free my hand as I have hundreds of scripts to IGNORE

**Comment by SPGoding** [comment]
Are glob patterns strong enough to describe those scripts which need to be ignored? Simply excluding files is much easier and faster than detecting the version in which the file is written.

**Comment by tremblestarman** [comment]
simply detect if 'as' is added behind 'execute'

**Comment by tremblestarman** [comment]
god fucks mobile github.

**Comment by tremblestarman** [comment]
( successfully assisted you to water an issue :D
