### ISSUE TITLE
Unexcepted variables recorded

### ISSUE THREAD

**Issue by MarsCloud** [SPGoding/datapack-language-server#178]
For example, I created a new datapack and add a new variable like this:
![bug-1](https://user-images.githubusercontent.com/43104628/69331863-75d5ef00-0c90-11ea-9a40-28b37999f214.gif)
and then the variable memory system recorded five variables with neither definitions nor references:
![image](https://user-images.githubusercontent.com/43104628/69331964-afa6f580-0c90-11ea-85fe-047bbb9ee18c.png)
so that they will show up everywhere.
![image](https://user-images.githubusercontent.com/43104628/69332320-64411700-0c91-11ea-92c8-5446a52030b0.png)

**Comment by SPGoding** [comment]
Can not reproduce.

**Comment by SPGoding** [comment]
@all-contributors

Add MarsCloud for bug and code
