### ISSUE TITLE
Maybe id: "enchantmentid" should output a warning too

### ISSUE THREAD

**Issue by MarsCloud** [SPGoding/datapack-language-server#181]
Example:
`id:"aqua_affinity" ×`
`id:"minecraft:aqua_affinity" 〇`
Now, no warning is output even in the previous example sentence.
In addition, character completion should be corrected accordingly.
![image](https://user-images.githubusercontent.com/43104628/69394874-36eb7c00-0d18-11ea-9185-51a5497590b9.png)

**Comment by SPGoding** [comment]
Duplicates 169.
