### ISSUE TITLE
Application of function alt click is unstable

### ISSUE THREAD

**Issue by ChenCMD** [SPGoding/datapack-language-server#191]
![image](https://user-images.githubusercontent.com/46134240/69908988-f33ef380-1436-11ea-8a7b-a23cb4b3d730.png)
This bug occurs immediately after loading.
If you rewrite the function name part, it will be applied normally.

**Comment by SPGoding** [comment]
Cannot reproduce :/

Does closing and opening the file again resolves this issue?

**Comment by ChenCMD** [comment]
Can only occur the first time it is opened
It will be fixed in the Reload Window, but it will be troublesome to do it every time it occurs

**Comment by SPGoding** [comment]
Simply closing the file tab (`Ctrl + W`) and opening the file again can fix this issue.

Anyway, a patch for this issue is on its way.
