### ISSUE TITLE
I want comment out TODO to output info

### ISSUE THREAD

**Issue by ChenCMD** [SPGoding/datapack-language-server#193]
This is another extension, but I want this feature to be implemented in DataPackHelper
![image](https://user-images.githubusercontent.com/46134240/69944694-39757f00-152b-11ea-923c-e4421e5b57ab.png)

**Comment by Arcensoth** [comment]
For what it's worth, here's another extension that lets you view all your TODOs in their own sidebar tab and even let's you define your own custom patterns:

https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree

This seems like more of a generic editor feature than a language-specific one to me.

**Comment by ChenCMD** [comment]
> For what it's worth, here's another extension that lets you view all your TODOs in their own sidebar tab and even let's you define your own custom patterns:
> 
> https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree
> 
> This seems like more of a generic editor feature than a language-specific one to me.

Did not know that such an extension exists :(
If so, SPGoding should decide

**Comment by SPGoding** [comment]
Yeah, I'm free!
