### ISSUE TITLE
Object name in text component is not changed in F2

### ISSUE THREAD

**Issue by ChenCMD** [SPGoding/datapack-language-server#194]
![image](https://user-images.githubusercontent.com/46134240/69968360-9722bf00-155d-11ea-9607-0152b583cf3c.png)
![image](https://user-images.githubusercontent.com/46134240/69968398-ac97e900-155d-11ea-920d-c06660c81991.png)

**Comment by SPGoding** [comment]
The support for text components was temporarily removed because of tons of bugs 🤦‍♀

This issue will likely be resolved when #170 is fixed, so I closed this issue as a duplicate

**Comment by SPGoding** [comment]
This is not a duplicate, sorry 🤦‍♀
