### ISSUE TITLE
New files aren't added to the cache when they're copied into the workspace

### ISSUE THREAD

**Issue by Arcensoth** [SPGoding/datapack-language-server#197]
I copied a folder with several functions in it (instead of creating them one by one) and they were not recognized as part of the workspace. The extension assumed they were not defined and could not auto-complete the folder name in `function` commands.

I tried reloading the window/extensions to see if the extensions would do some sort of re-scan, but the issue persisted. I then tried deleting the cache file so the extension would be forced to regenerate it, which fixed the issue.

Is it possible to make the extension scan over the cache and compare it with the actual directory structure? Perhaps on-demand with a certain event or keyboard shortcut for the few cases when it does occur, instead of costing performance overall. Or maybe VSCode/LSP offers some kind of "file copied" event hook? (Although the latter might not solve cases where the file/folder was copied from outside of VSCode...)

**Comment by SPGoding** [comment]
To be honest, the extension _should_ add all unknown files to cache when starting. Not sure where's the problem, but I will try to fix it.
And yes, I will try my best to make it never happen again to reload the window just because of the silly cache file not updating.
