### ISSUE TITLE
Feature request: provide an error for scoreboard (fake) player names over 40 characters

### ISSUE THREAD

**Issue by Arcensoth** [SPGoding/datapack-language-server#199]
This is a feature request/enhancement.

The game does not handle invalid scoreboard player names very well. There is a hard limit of 40 characters, but it is not a syntax error and does not appear in the game log. Not only that, but the in-game error message is very unclear about the underlying cause:

![image](https://user-images.githubusercontent.com/1885643/70402448-65987080-1a01-11ea-8801-7118dcf789c1.png)

The proposed feature is to add this capability to the language server. Ideally it would check when a player name is being used in the context of a scoreboard entry, and provide an error message if it is over 40 characters.

Is this a reasonable request? How difficult would it be to implement?

**Comment by SPGoding** [comment]
The limit for normal entity names is 16, while that for score holder names is 40. Also I'd like to treat this as a bug.

This is a really complex thing to deal with :/
