### ISSUE TITLE
Auto completion order for coordinates

### ISSUE THREAD

**Issue by mathaym25** [SPGoding/datapack-language-server#203]
Wherever auto-completion for coordinates works, it offers us the choice between `^` and `~`, in that order.
This means that tapping TAB at this time will cause us to write `^`.
And we must use the mouse or the arrow keys to write `~`.

However, `^` is much less used than `~`, so it would be logical (if possible) to reverse the order in which these two characters are proposed.

**Comment by SPGoding** [comment]
@all-contributors

Add mathaym25 for bug and ideas!
