### ISSUE TITLE
Provide completions for non-defininition comments

### ISSUE THREAD

**Issue by ChenCMD** [SPGoding/datapack-language-server#207]
![image](https://user-images.githubusercontent.com/46134240/70996779-d719a280-2116-11ea-8543-ec0427750f43.png)

**Comment by SPGoding** [comment]
`#define`  ✏️

**Comment by ChenCMD** [comment]
It's a terrible mistake :(
I didn't notice typo because if I use a space in the commented out line, a completion candidate appears unconditionally.

**Comment by SPGoding** [comment]
Oh yes, that's a problem
