### ISSUE TITLE
Entity's UUID is illegal in command data merge entity

### ISSUE THREAD

**Issue by yulongjiuqiu** [SPGoding/datapack-language-server#208]
the command
`data merge entity 68b6b73a-f79c-49ee-a8ea-471911f553c6 {Item:{tag:{display:{Name:'{"translate":"pl.frame.ldp"}'}}}}`
"68b6b73a-f79c-49ee-a8ea-471911f553c6" is underlined in red

**Comment by SPGoding** [comment]
Caused by the fix of #199.

**Comment by SPGoding** [comment]
@all-contributors

Add yulongjiuqiu for bug :bug:
