### ISSUE TITLE
PersistenceRequired NBT tag is not included.

### ISSUE THREAD

**Issue by ThePixelatedCactus** [SPGoding/datapack-language-server#213]
The Boolean NBT tag, PersistenceRequired, is not on the list of NBT tags in the plugin despite having a function in Minecraft.
![image](https://user-images.githubusercontent.com/26680036/71218479-7ef9b200-2276-11ea-99d1-4fa3e9ecfca2.png)

**Comment by SPGoding** [comment]
@all-contributors

Add ThePixelatedCactus for bug

**Comment by SPGoding** [comment]
What is your full command? The `PersistenceRequired` tag does exist.
![image](https://user-images.githubusercontent.com/15277496/71218621-c8063200-2287-11ea-8bea-1810e1fd589d.png)
