### ISSUE TITLE
I want to be able to define a scoreboard

### ISSUE THREAD

**Issue by ChenCMD** [SPGoding/datapack-language-server#222]
Currently it is inconvenient to use "scoreboard objectives add" because objects are not added to completion
`#define objective <objectName> [Comments]`
I want the scoreboard to be defined like this and displayed in the completion list

**Comment by ChenCMD** [comment]
Is this a bug...?

**Comment by SPGoding** [comment]
Hmm, players should be able to define those things by using comments, so I treated it as a bug.
