### ISSUE TITLE
'y_rotation' selector slot should be seen as 'a circle'

### ISSUE THREAD

**Issue by OctupusTea** [SPGoding/datapack-language-server#232]
Using a selector such as `@a[y_rotation=135..-135]` produces an error `The minimum value 135 is larger than the maximum value -135.` .

However, this works in Minecraft flawlessly. Y rotations should be deemed as a circle or a modulo thing, instead of a number line from -180 to 180.

**Comment by SPGoding** [comment]
@all-contributors

Add OctupusTea for bugs.
