### ISSUE TITLE
player_head SkullOwner problem

### ISSUE THREAD

**Issue by RevonZev** [SPGoding/datapack-language-server#235]
This code:
`give @p minecraft:player_head{display:{Name:"{\"text\":\"Zombie Pigman\"}"},SkullOwner:"MHF_PigZombie"} 1`

The `SkullOwner:"MHF_PigZombie"` display problem _Expected a compound tag instead of a string tag._
When you execute this command, it does give you the player head with the correct skin.

**Comment by SPGoding** [comment]
This bug is not that easy to fix, since the current syntax of NBT Doc doesn't support multiple types of a single tag.

I guess this will be fixed next year.
