### ISSUE TITLE
Throws an exception if you specify a UUID for the teleport selector

### ISSUE THREAD

**Issue by ChenCMD** [SPGoding/datapack-language-server#241]
![image](https://user-images.githubusercontent.com/46134240/71767729-7ed60380-2f52-11ea-9586-491c3e63b266.png)

**Comment by SPGoding** [comment]
I hate the syntax of `teleport` command. Even _Minecraft_ itself dislikes it:
![image](https://user-images.githubusercontent.com/15277496/71769517-1ce0b400-2ee8-11ea-8718-84cca7ca39e5.png)
