### ISSUE TITLE
Internationalization and Localization

### ISSUE THREAD

**Issue by SPGoding** [SPGoding/datapack-language-server#246]

**Comment by SPGoding** [comment]
@ChenCMD Would you like to help me translate this extension into Japanese (ja)? I've written some instructions at [CONTRIBUTING.md](https://github.com/SPGoding/datapack-language-server/blob/1.12.0/CONTRIBUTING.md) if you'd like to take a look ❤️

**Comment by ChenCMD** [comment]
I will try it
