### ISSUE TITLE
Add cache regeneration button

### ISSUE THREAD

**Issue by ChenCMD** [SPGoding/datapack-language-server#247]
Caching can cause problems
At that time, it is troublesome to delete .datapack from the folder, so can't I put that button in the place of this image?
![image](https://user-images.githubusercontent.com/46134240/72040200-2a80aa00-32eb-11ea-821d-e168894d1684.png)

**Comment by SPGoding** [comment]
Sure, will add.
And could you please tell me how this happened? Maybe I can try fixing it (agaaaain).
