### ISSUE TITLE
nbtPath throws warning on some syntax

### ISSUE THREAD

**Issue by ChenCMD** [SPGoding/datapack-language-server#271]
The syntax I have confirmed is:
・Test[0].[0]
・Test[0][0]

**Comment by SPGoding** [comment]
Minecraft even allows something like `foo{bar: "qux"}[0]`, which makes no sense. However, it doesn't allow something like `foo[0]{bar: "qux"}` which is definitly useful in many cases. Crazy Mojang 😭
