### ISSUE TITLE
Namespace ideas are providing links.

### ISSUE THREAD

**Issue by dragon3025** [SPGoding/datapack-language-server#331]
I have some defined scores and functions and there's no yellow line under them when referenced. I can't ctrl+click to open them and there isn't any suggestions that pop up when I try to type them out.

I believe this is the same as this issue #73: https://github.com/SPGoding/datapack-language-server/issues/73

EDIT: I'm using v1.11.14

**Comment by SPGoding** [comment]
Is this still an issue in the newly released *1.13.0*?

If so, can regenerating the cache (by pressing `Ctrl + Shift + P` and typing `Datapack: Regenerate Cache` ) fix this issue?

**Comment by dragon3025** [comment]
Sorry, I haven't used Visual Studio Code for too long, and didn't see where the version number was. I'm not using 1.11.14 I'm using 1.13.0.

Just now I used Ctrl+Shift+P and a box showed up. I typed what you said and hit enter, but nothign happened.

**Comment by SPGoding** [comment]
I believe this is the same issue as #336 which was just fixed. Please tell me whether this still exists in lately released **1.13.1**.

**Comment by dragon3025** [comment]
I'm using 1.13.1 and it's still not working even after trying `ctrl+shift+p` and `Datapack: Regenerate Cache` again.

**Comment by SPGoding** [comment]
That's really sad :sob:

Do you have a datapack as a root folder of the workspace on the left panel of VScode? If not, try selecting `File` -> `Open Folder` to open the root folder (parent of `data` and `pack.mcmeta`) of a datapack. Sorry I can't really figure out what the problems are :/

**Comment by dragon3025** [comment]
I have a root folder of a Datapack open. I got some message earlier saying I no longer needy a cache folder and it can be deleted, so I did. Is that related to this?

**Comment by SPGoding** [comment]
> I no longer needy a cache folder and it can be deleted, so I did. Is that related to this?

Nope, that's intended.

> Strangely the links are back, even though they weren't a second ago.

That's really weird. I wish this issue didn't show again when you restart :/

**Comment by dragon3025** [comment]
Okay, after adding to some functions, I noticed nothing was happening. Finally I opened some of the codes in notepad++ and realized that my most recent additions that are showing up in notepad++ wasn't showing up in visual studio. I closed the folder, then reopened it and my changes that only showed up in notepad++ are back, but the links are now broken again.

**Comment by dragon3025** [comment]
Okay, I just got this when loading Visual Studio Code:

> Request initialize failed with message: c:\Users\cntdr\AppData\Roaming\Code\User\workspaceStorage\9d9c6fdade69814a618324aeee725892\SPGoding.datapack-language-server\cache.json: Unexpected token

**Comment by SPGoding** [comment]
That's strange. Would you please send me the content of the file `c:\Users\cntdr\AppData\Roaming\Code\User\workspaceStorage\9d9c6fdade69814a618324aeee725892\SPGoding.datapack-language-server\cache.json`?

**Comment by dragon3025** [comment]
[cache.zip](https://github.com/SPGoding/datapack-language-server/files/4238288/cache.zip)

**Comment by SPGoding** [comment]
Please tell me again if this still is an issue. Really sorry that I have no idea what's going wrong :cry:

**Comment by dragon3025** [comment]
After the update I regenerated the pack or re-opened the folder (I forget which) and it's been working fine ever since. I'll post again if something bad happens. Thanks for working on this.

**Comment by SPGoding** [comment]
Finally! Honestly I did nothing about this and still don't know the reason why this was happening :/

Thanks for your patience anyway. Happy _mcfunctioning_!
