### ISSUE TITLE
Extension refers to version 1.16 despite having datapackLanguageServer.env.version: 1.15

### ISSUE THREAD

**Issue by ChenCMD** [SPGoding/datapack-language-server#361]
![image](https://user-images.githubusercontent.com/46134240/75761840-17370b80-5d7d-11ea-9900-89d39c4ec54b.png)
Restarting and regenerating the cache didn't change anything :(

**Comment by SPGoding** [comment]
There's another option named `Datapack Language Server > Env: Data Version` controlling this. Try changing it to `1.15.2` ;D

The option you changed only affect command syntax, not completion data
