### ISSUE TITLE
Use of formatter causes duplicate and increased quotes

### ISSUE THREAD

**Issue by ChenCMD** [SPGoding/datapack-language-server#368]
![image](https://user-images.githubusercontent.com/46134240/76846100-4e301580-6883-11ea-9748-3006e92e0cb3.png)
![image](https://user-images.githubusercontent.com/46134240/76846121-55efba00-6883-11ea-8fac-e723e226bb70.png)

**Comment by SPGoding** [comment]
I don't know when, but this was fixed ;D
