### ISSUE TITLE
Weird auto-completion in text components

### ISSUE THREAD

**Issue by misode** [SPGoding/datapack-language-server#384]
Strings inside components don't show auto-completion when you have typed `"`.
![image](https://user-images.githubusercontent.com/17352009/78450633-4db7bd00-7680-11ea-88b4-d3a14a3da924.png)
![image](https://user-images.githubusercontent.com/17352009/78450636-54463480-7680-11ea-873a-72200360717f.png)
![image](https://user-images.githubusercontent.com/17352009/78450653-72ac3000-7680-11ea-87ee-f1ef9e1db888.png)
![image](https://user-images.githubusercontent.com/17352009/78450661-7b046b00-7680-11ea-8f94-bbd986b46bcb.png)

This also affects fields like scoreboard objectives, storage IDs. In the case of namespaced resource locations, this can be problematic. Consider the following scenario:

![image](https://user-images.githubusercontent.com/17352009/78450851-d420ce80-7681-11ea-8240-477ac6464bab.gif)

**Comment by SPGoding** [comment]
![#384](https://user-images.githubusercontent.com/15277496/79092945-34fe7580-7d18-11ea-9262-560bda1f1979.gif)
Will be fixed in next version
