### ISSUE TITLE
Autocompletion of strings in JSON format

### ISSUE THREAD

**Issue by mathaym25** [SPGoding/datapack-language-server#385]
~~It works very well in tellraw, title, etc.
But it would be even better if it worked in the NBT `Text1`, `Text2`, `Text3` and `Text4` of the panels as well as for the NBT `CustomName`, `Name` and `Lore`.~~

JSON auto completion just doesn't work with `Name` and `Lore` with /give and /replaceitem.
(Thanks misode for correction)
![Screenshot 04-04-2020 à 17h03m02s](https://user-images.githubusercontent.com/35702771/78454271-4cde5580-7697-11ea-979d-e4a519609e90.png)

**Comment by misode** [comment]
Cannot reproduce
![image](https://user-images.githubusercontent.com/17352009/78451405-b8b7c280-7685-11ea-98f9-f0b2f7085b51.png)
