### ISSUE TITLE
Auto-complete sometimes gives no results in selectors

### ISSUE THREAD

**Issue by misode** [SPGoding/datapack-language-server#386]
This happens when you press Escape and then press Ctrl+Space.

![QE9NiYkKt4](https://user-images.githubusercontent.com/17352009/78451319-3e873e00-7685-11ea-99af-48a57be391c1.gif)

**Comment by SPGoding** [comment]
Fixed. Also fixed the completions for quoted keys.

![#386](https://user-images.githubusercontent.com/15277496/79053919-97ffe780-7c06-11ea-965d-5f76b32f833f.gif)
