### ISSUE TITLE
Missing gamerules

### ISSUE THREAD

**Issue by mathaym25** [SPGoding/datapack-language-server#387]
The gamerules `doPatrolSpawning` and `doTraderSpawning` are not recognized, and the `immediateRespawn` gamerule doesn't exist on Java Edition.

![Screenshot 04-04-2020 à 18h51m22s](https://user-images.githubusercontent.com/35702771/78456689-6d151100-76a5-11ea-9ca2-4a51fab37512.png)

**Comment by SPGoding** [comment]
Duplicates #364
