### ISSUE TITLE
Rotation works fine with one argument

### ISSUE THREAD

**Issue by ChenCMD** [SPGoding/datapack-language-server#410]
Ex. : `{Rotaion:[90.0f]}`

**Comment by SPGoding** [comment]
Although `{Rotation:[90.0f]}` works exactly the same as `{Rotation:[90.0f,0.0f]}` in some cases, there are other cases that will be broke by it. For example,
```mcfunction
execute if entity @s[nbt={Rotation:[90.0f]}]
```
will match both `{Rotation:[90.0f,0.0f]}` and `{Rotation:[0.0f,90.0f]}`.

I don't think it's safe to only write one element in `Rotation`, so sorry, this works as intended.

**Comment by SPGoding** [comment]
As also request by other users at [Discord](https://discordapp.com/channels/666020457568403505/666020458453270535/729811165697540260) I will add a new setting to configure the behavior of length checking.
