### ISSUE TITLE
"with" text component seems not supported

### ISSUE THREAD

**Issue by misode** [SPGoding/datapack-language-server#414]
The `"with"` property in text component is used in combination with `"translate"`. However it isn't suggested, it's value (which is a list of JSON text components) isn't giving any suggestions, and there are some invalid errors coming from it.

<img width="342" alt="Code_vK5htVhH28" src="https://user-images.githubusercontent.com/17352009/80290500-9de8e300-8745-11ea-92a1-9fa9f81cc430.png">
<img width="360" alt="Code_Y0rLIqhxmh" src="https://user-images.githubusercontent.com/17352009/80290519-ccff5480-8745-11ea-8ccc-ad5fbc7f6395.png">

**Comment by SPGoding** [comment]
![image](https://user-images.githubusercontent.com/15277496/80292201-51d47900-871a-11ea-87a1-60fd8997b4af.png)

Already fixed in 2.0.0 ;D
