### ISSUE TITLE
Nbtdoc type is not displayed properly when the language is "ja"

### ISSUE THREAD

**Issue by ChenCMD** [SPGoding/datapack-language-server#416]
![image](https://user-images.githubusercontent.com/46134240/80297619-b564b200-87bf-11ea-823e-56de1956a91c.png)
![image](https://user-images.githubusercontent.com/46134240/80297623-bdbced00-87bf-11ea-8b0b-5f2037ad9563.png)

**Comment by SPGoding** [comment]
The `%0%` part was missing in [`nbtdoc.type`'s translation](https://dhp.spgoding.com/translate/datapack-helper-plus/service-messages/ja/?q=nbtdoc.type&checksum=&offset=#memory) ;D
