### ISSUE TITLE
Even if you change the name of function, only the cache is changed

### ISSUE THREAD

**Issue by ChenCMD** [SPGoding/datapack-language-server#421]

**Comment by SPGoding** [comment]
:thinking: Sorry, I didn't get what you meant.

**Comment by ChenCMD** [comment]
There was not enough explanation:(
When changing the function name using F2, only the cache is changed, the actual function file position and the function command path are not changed.
However, it certainly happens, but it does not always happen.

**Comment by ChenCMD** [comment]
I'm not sure about the details, but it happened even with v2.0.0.
