### ISSUE TITLE
Bug?: Interpreter incorrectly marks it as an error

### ISSUE THREAD

**Issue by ShadowCreator250** [SPGoding/datapack-language-server#446]
Please take a look at the screenshot.

The interpreter thinks there should be the end of the file but I'm in the middle of the line. 
I think the problem could be linked to the Lore tag.

Thx for the amazing language server btw. The syntax suggestions are really helpful.

![Unbenannt](https://user-images.githubusercontent.com/52125935/80736696-c4769780-8b12-11ea-8e4f-cef22459d615.PNG)

**Comment by SPGoding** [comment]
Each text component in `Lore` has to be quoted individually. e.g.
```mcfunction
give @s stone{display: {Lore: ['{"text": "this is something"}', '{"text": "but no errors shown"}']}}
```
