### ISSUE TITLE
Text1, Text2 etc in oak_sign register as 'Unknown key'

### ISSUE THREAD

**Issue by AndanteDevs** [SPGoding/datapack-language-server#452]
![image](https://user-images.githubusercontent.com/36608902/81285756-e6fb3a00-9057-11ea-9995-f3cb5707a517.png)

`2.0.0` @ `20w19a`

Cannot reproduce this with other sign types

**Comment by AndanteDevs** [comment]
Log: https://hastebin.com/egoqabupiv.cs
There's some errors to do with fetching `20w19a`

**Comment by SPGoding** [comment]
TL;DR: Changing `datapack.env.dataVersion` to `20w18a` can temporarily resolve this problem.

The [Yurihaia/mc-nbtdoc](github.com/Yurihaia/mc-nbtdoc) repository hasn't been updated to 20w19a, so there are errors when fetching it. After 10 times of failing, the language server will use the fallback nbtdoc bundled in the extension which is for 20w17a and doesn't include `oak_sign`. Yurihaia fixed the `oak_sign` problem in the nbtdoc for 20w18a, so changing `datapack.env.dataVersion` to `20w18a` can fix this.
