### ISSUE TITLE
The tp command duplicates the alias if you try to fill in the selector later with the previous arguments filled in.

### ISSUE THREAD

**Issue by ChenCMD** [SPGoding/datapack-language-server#460]
![image](https://user-images.githubusercontent.com/46134240/81501763-fc50bc80-9314-11ea-9d1b-7d7453224772.png)

**Comment by SPGoding** [comment]
![image](https://user-images.githubusercontent.com/15277496/85217462-0ecc0600-b357-11ea-8aa7-a303025f1665.png)

I can't reproduce this 🤔
