### ISSUE TITLE
cmdVersion setting has invalid type

### ISSUE THREAD

**Issue by misode** [SPGoding/datapack-language-server#461]
Even though this user setting is not set/modified, it shows an error.
![image](https://user-images.githubusercontent.com/17352009/81509839-c0662900-930d-11ea-8090-e4a7bfe4aac7.png)

Clicking to edit in JSON shows that there are two options. Those do not get rid of the error message.
![image](https://user-images.githubusercontent.com/17352009/81509879-08854b80-930e-11ea-8503-44dba44a83af.png)

**Comment by SPGoding** [comment]
**Thanks for your report!**

However, we are actually already tracking this issue in **SPGoding/vscode-datapack-helper-plus#1**.

I know you have never seen that repository before, so never mind.

**Quick Links**
Okay this is not fun, I will get rid of this.
