### ISSUE TITLE
error when autocompleting execute subcommands.

### ISSUE THREAD

**Issue by Command-Master** [SPGoding/datapack-language-server#477]
whenever I type `execute ` and try autocomplete the subcommand (if/unless/store/run) I get the following errors: ```
[Error - 20:14:03] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read property 'entries' of undefined
  Code: -32603 
[Error - 20:14:03] Request textDocument/signatureHelp failed.
  Message: Request textDocument/signatureHelp failed with message: Cannot read property 'entries' of undefined
  Code: -32603 ```

**Comment by SPGoding** [comment]
Duplicate of #475.
