### ISSUE TITLE
Add "minecraft:job_site" into villager's nbt memories  is illegal.

### ISSUE THREAD

**Issue by yulongjiuqiu** [SPGoding/datapack-language-server#495]
The command:
`summon villager ~ ~ ~ {Brain:{memories:{"minecraft:job_site":{pos:[I;47,65,199],dimension:"minecraft:overworld"}}}`

"minecraft:job_site" is underlined with yellow.(未知的键)

**Comment by SPGoding** [comment]
Duplicate of Yurihaia/mc-nbtdoc#8

**Comment by SPGoding** [comment]
-> Yurihaia/mc-nbtdoc#8
