### ISSUE TITLE
NBTPath works fine even if you put a dot at the end.

### ISSUE THREAD

**Issue by ChenCMD** [SPGoding/datapack-language-server#498]
![image](https://user-images.githubusercontent.com/46134240/85207251-6c198480-b362-11ea-8761-56ff5e581a4c.png)
![image](https://user-images.githubusercontent.com/46134240/85207265-83587200-b362-11ea-8840-9a50599ee02c.png)

**Comment by SPGoding** [comment]
I don't want to fix this lol
