### ISSUE TITLE
Throws Unknown key for unique nbt.

### ISSUE THREAD

**Issue by ChenCMD** [SPGoding/datapack-language-server#515]
![image](https://user-images.githubusercontent.com/46134240/85676083-3c230600-b701-11ea-913c-619d75ff9cef.png)
This is not limited to ActiveEffects, but all unique NBT tags (eg ArmorItems, Inventory, Duration, etc.).

**Comment by SPGoding** [comment]
It requires a lot of work to fix this bug permanently; I'd like to just downgrade the severity of this diagnostic from warning (yellow line) to hint (short gray line)

**Comment by SPGoding** [comment]
Reopen for now, in case I want to fix this thoroughly in the future
