### ISSUE TITLE
"Fix all auto-fixable problems in the workspace" If you want to modifications to the function file that is not open, modify while maintaining a warning or error.

### ISSUE THREAD

**Issue by ChenCMD** [SPGoding/datapack-language-server#519]
![image](https://user-images.githubusercontent.com/46134240/85680288-1e57a000-b705-11ea-9b6f-201e84a82d08.png)

**Comment by SPGoding** [comment]
I believe the error will disappear after a while :thinking:

The `fix all in workspace` action is quite slow, I might want to add a new progress bar in the next version to show the progress of updating.
