### ISSUE TITLE
tag.Enchantments accepts lvl:0 and id:"".

### ISSUE THREAD

**Issue by ChenCMD** [SPGoding/datapack-language-server#531]
This should be used only for enchantment effects.
![image](https://user-images.githubusercontent.com/46134240/85844181-44e90a00-b7dd-11ea-89e2-e14821708d52.png)

**Comment by SPGoding** [comment]
The `lvl: 0` part will hopefully be fixed by Yurihaia/mc-nbtdoc#9.

And honestly I don't want to fix the `id: ""` part even if it's valid
