### ISSUE TITLE
#define custom NBT tag paths

### ISSUE THREAD

**Issue by PsiGreenEx** [SPGoding/datapack-language-server#546]
My ideas for more define options are:
`storage_path`: Define custom NBT tag paths for when you are using data storage.
~~`dimension` and `dimension_type`: Define custom dimensions and dimension types.~~

Edit: Second one was already suggested, sorry.

**Comment by SPGoding** [comment]
> ~~`dimension` and `dimension_type`: Define custom dimensions and dimension types.~~
Thanks for reminding, I almost forgot that! Now tracked in #547.

The custom NBT path definition would be really nice to have, however it requires some work to compile the NBT paths to the format the language server uses internally, so don't expect it come true soon ;D

**Comment by SPGoding** [comment]
Duplicate of #657
