### ISSUE TITLE
SkullOwner NBT HoverInfomation only shows "Or".

### ISSUE THREAD

**Issue by ChenCMD** [SPGoding/datapack-language-server#575]
![image](https://user-images.githubusercontent.com/46134240/87158283-73490800-c2fa-11ea-939d-07377826dd7d.png)

**Comment by SPGoding** [comment]
The content of `SkullOwner` can be either `{ Id: [...], Name: "", Properties: {textures: []} }` or just a simple string with the player name, so this works as intended
