### ISSUE TITLE
TextComponent colors do not accept uppercase color codes (eg #FFFFFF)

### ISSUE THREAD

**Issue by ChenCMD** [SPGoding/datapack-language-server#586]

**Comment by harvanchik** [comment]
I noticed this was only happening when the first character after the # was a capital letter.

**Comment by pca006132** [comment]
https://github.com/SPGoding/datapack-json/blob/dc01940fd05e743f04e88875ea1e1f83f9c6e6f1/src/shared/text_component.json#L358

```json
"pattern": "#[0-9a-f]{1,6}"
```
Just change it to the following should be fine?
```json
"pattern": "#[0-9a-fA-F]{1,6}"
```
