### ISSUE TITLE
Namespace IDs aren't providing links

### ISSUE THREAD

**Issue by dragon3025** [SPGoding/datapack-language-server#611]
I've had this problem before : [#331](https://github.com/SPGoding/datapack-language-server/issues/331), but now it's back.

**Comment by SPGoding** [comment]
This is frustrating 🤦 

Does this bug affect all namespaced IDs or only a portion of them ?

**Comment by dragon3025** [comment]
So far I have structures, functions, scores, tags, and predicates that I've referenced and it didn't provide them as suggestions when I referenced them and they don't provide links.

**Comment by SPGoding** [comment]
Please tell me if you're still encountering this in **3.0.0**

**Comment by dragon3025** [comment]
It seems to be working fine.

**Comment by SPGoding** [comment]
Good to know ;D
