### ISSUE TITLE
The set_lore/set_name entity appears as an invalid option but is required in-game

### ISSUE THREAD

**Issue by ChenCMD** [SPGoding/datapack-language-server#637]
![image](https://user-images.githubusercontent.com/46134240/89508991-abfcd400-d809-11ea-9bba-4a0d8b7ff092.png)
![image](https://user-images.githubusercontent.com/46134240/89509244-07c75d00-d80a-11ea-9904-7868f2a57233.png)

**Comment by SPGoding** [comment]
What's the type of this loot table?

**Comment by ChenCMD** [comment]
empty

**Comment by SPGoding** [comment]
Then this is intended. Loot tables of the `empty` type cannot provide the necessary context `this` requires.
