### ISSUE TITLE
@within also blocks the resource path of the function header

### ISSUE THREAD

**Issue by ChenCMD** [SPGoding/datapack-language-server#643]

**Comment by SPGoding** [comment]
Could you please provide an example?

**Comment by ChenCMD** [comment]
![image](https://user-images.githubusercontent.com/46134240/90162243-4f805280-ddcf-11ea-91ba-d1e4096e7d0b.png)

**Comment by SPGoding** [comment]
The function ID in the first line is supposed to be the same ID as the current function.
