### ISSUE TITLE
Predicate for "damage_source_property" in loot_tables don't have "type" property

### ISSUE THREAD

**Issue by Enn83** [SPGoding/datapack-language-server#659]
I think I found a "_bug_" in the predicate **minecraft:damage_source_properties** for loot_tables. They aren't type property. For example in the file turtle.json the bowl recipe have predicate > is_lightning, instead of predicate > type > is_lightning. The Minecraft version work in the game, but the second (with type) suggested by DPH+ don't work in Minecraft, and the loot is looted regardless of the predicate. I think pictures will be better than words !

Minecraft Ver (work fine) :
![bowl_MCver](https://user-images.githubusercontent.com/46783975/90321878-2803c400-df4e-11ea-934f-a432b18be954.jpg)

DPH+ Ver (predicate ignored) :
![bowl_DHP+ver](https://user-images.githubusercontent.com/46783975/90321879-289c5a80-df4e-11ea-8947-fc7635b5c72e.jpg)

**Comment by SPGoding** [comment]
Please uninstall the "Datapack Helper Plus (JSON)" extension; it's the bad one. The language server (Data-pack Helper Plus) can provide support for JSONs correctly.
