### ISSUE TITLE
Incorrect map key suggestions

### ISSUE THREAD

**Issue by misode** [SPGoding/datapack-language-server#666]
![image](https://user-images.githubusercontent.com/17352009/90334786-532ef780-dfd0-11ea-9284-9ffadbe65a46.png)
![image](https://user-images.githubusercontent.com/17352009/90334759-34c8fc00-dfd0-11ea-9cbc-71e91a336b69.png)

**Comment by SPGoding** [comment]
Looks like this is no longer an issue :eyes:

**Comment by SPGoding** [comment]
This is still an issue: https://discordapp.com/channels/666020457568403505/666020458453270535/776309942826827776
