### ISSUE TITLE
Custom recipe type "minecraft:smithing" expects a result string when it's supposed to be a tag compound

### ISSUE THREAD

**Issue by eggohito** [SPGoding/datapack-language-server#685]
The JSON auto-completion for custom recipes expects the `result` tag to be a string even though the `result` tag is supposed to be a tag compound;

If the `result` tag is a tag compound:
![image](https://user-images.githubusercontent.com/66972816/91109715-5e5be480-e6ae-11ea-925e-bd6c0a5f3e9f.png)

If the `result` tag is a string:
![image](https://user-images.githubusercontent.com/66972816/91109782-92370a00-e6ae-11ea-838a-1ed2982098b1.png)

**Comment by SPGoding** [comment]
The behavior of DHP is correct.

**Comment by SPGoding** [comment]
Oops, nvm
