### ISSUE TITLE
Completing suggestion with tab in already quotation marks will add another set of quotation marks

### ISSUE THREAD

**Issue by vanjmali** [SPGoding/datapack-language-server#686]
![image](https://user-images.githubusercontent.com/31445914/91160285-7f7dfe80-e6c9-11ea-8e38-37830ef3d52e.png)
![image](https://user-images.githubusercontent.com/31445914/91160236-6d03c500-e6c9-11ea-969b-190e4a9cd7b3.png)
Sometimes auto-suggestion doesn't appear, usually after tab completion in `hoverEvent` for example, but it does appear when you add the quotation marks but the completion will add another set of quotation marks in the quotations marks

**Comment by SPGoding** [comment]
Duplicate of #677
