### ISSUE TITLE
[Suggestion] Some command argument shouldn't suggest autocomplete

### ISSUE THREAD

**Issue by oOBoomberOo** [SPGoding/datapack-language-server#689]
![](https://i.imgur.com/2ZoVmtF.png)

This is just a nitpick and not that important but command like `scoreboard objectives add ...` doesn't really make much sense to get the objective name to autocomplete.

**Comment by SPGoding** [comment]
The user might want to select an existing objective (e.g. `bb.pl.enum`) and then change the last part of the name to something else, so this works as intended
