### ISSUE TITLE
Getting errors when opening most functions after last update

### ISSUE THREAD

**Issue by eke0909** [SPGoding/datapack-language-server#700]
Everything worked yesterday when I was editing a function, but today, when I opened it most of the functions in the folder, doesn't work and I'm getting a bunch of errors.
Some of the functions are working fine, but most of them not at all.
I have also tried an older version and I get the same problem there.

I don't really know what has happened but I noticed that there was a new update released today, so I guess that's the cause.
So please tell me if I have missed something or if it is the update.

Here are the errors that I found.
```
[Error - 16:08:55] Request textDocument/foldingRange failed.
  Message: Request textDocument/foldingRange failed with message: this.activeCase is not a function
  Code: -32603 
[Error - 16:08:55] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: this.activeCase is not a function
  Code: -32603 
[Error - 16:08:56] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: this.activeCase is not a function
  Code: -32603 
[Error - 16:13:24] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: this.activeCase is not a function
  Code: -32603 
```

**Update** 
After looking through them again it seems like the problem only occurs when something is getting written out, I think it doesn't matter if it is by using tellraw, a bossbar etc.

**Comment by Mizab1** [comment]
I was also getting the exact error

**Comment by eke0909** [comment]
It seems to work just fine after changing to an older version, so if anyone else has the same problem you should be able to temporarily go back to an older version.
