### ISSUE TITLE
missing NBT tag for Player

### ISSUE THREAD

**Issue by end-user** [SPGoding/datapack-language-server#722]
The Player has a `previousPlayerGameType` NBT introduced in 1.16.  I don't know where in the code these are defined or I'd submit a PR.

**Comment by MulverineX** [comment]
@end-user https://github.com/Yurihaia/mc-nbtdoc

**Comment by SPGoding** [comment]
Those NBT data are stored in https://github.com/Yurihaia/mc-nbtdoc

**Comment by MulverineX** [comment]
https://github.com/Yurihaia/mc-nbtdoc/blob/master/minecraft/entity/mob/player.nbtdoc

**Comment by SPGoding** [comment]
Duplicate of Yurihaia/mc-nbtdoc#25
