### ISSUE TITLE
Comments not colored correctly (or appropiately)

### ISSUE THREAD

**Issue by SirWindfield** [SPGoding/datapack-language-server#725]
Hey!

Comments inside of `.mcfunction` files are not highlighted as comments but rather as normal text. Here is an example with the standard VSCode Light Theme. The current behaviour is independent of the theme I use, comments always have the same color as normal text would have.

How is is right now:
![image](https://user-images.githubusercontent.com/5113257/97080107-5c07ff00-15f9-11eb-8ace-a9bdf66656d1.png)

As a comparison, here is a Rust file highlighted:
![image](https://user-images.githubusercontent.com/5113257/97080117-6fb36580-15f9-11eb-854f-6ca84135cf37.png)

**Comment by SPGoding** [comment]
This is actually intended: punctuation and comments are not colorized by DHP. You might want to install Arcensoth's [language-mcfunction](https://marketplace.visualstudio.com/items?itemName=arcensoth.language-mcfunction) as well.
