### ISSUE TITLE
DHP does not recognize multiline @within syntax

### ISSUE THREAD

**Issue by pie-flavor** [SPGoding/datapack-language-server#733]
Per [IMP-Doc](https://github.com/Arcensoth/imp-spec/blob/master/docs/imp_doc.md#function-annotation-within), `@within` can be used in a single-line form, or in a multiline form indented by two spaces. However, DHP does not recognize this syntax, which breaks its access modifier protection. DHP instead seems to only recognize it when they are split each into their own single-line form of the `@within` tag.

**Comment by ChenCMD** [comment]
hmmm, I can't reproduce it. Could you please provide an example?

**Comment by pie-flavor** [comment]
It seems to have vanished. Huh. But it was definitely there, and definitely persisting across file-saves and tab-reopens. Perhaps something transient? It was saying that it expected "tag", "function", etc., but found "". But there definitely wasn't any formatting error. The comment I was using was
```mcfunction
# @within
#   chess:get_active_spaces/horiz_left
#   chess:get_active_spaces/horiz_left/next
```

**Comment by pie-flavor** [comment]
Aha. It triggers if there is a space after `@within`.

**Comment by SPGoding** [comment]
That's intended then ;D

If there's a space after `@within`, DHP would expect you to write them in the same line.
