### ISSUE TITLE
Extremely bad error reporting when checking contents of books

### ISSUE THREAD

**Issue by Devon7925** [SPGoding/datapack-language-server#742]
![image](https://user-images.githubusercontent.com/22968971/98902466-0776d780-2473-11eb-9827-0cbe9c7deaef.png)

**Comment by SPGoding** [comment]
Changing `"z"` to `'"z"'` can fix this error.

```mcfunction
execute if entity @s[nbt={Inventory:[{id:"minecraft:writable_book",tag:{pages:['"z"']}}]}] run tag @s add fail
```

Thanks for the report, I will look into it soon!
