### ISSUE TITLE
Make fake players #declare-able

### ISSUE THREAD

**Issue by NeunEinser** [SPGoding/datapack-language-server#744]
Would be nice to be able to avoid mistyping a fake scoreboard player and have a completion list for them in general.
Possibly per objective? Could just be a global list as well, though. I usually only use 1 or 2 objectives with fake players anyways. Should have visibility options like usual.

**Comment by SPGoding** [comment]
```mcfunction
#declare score_holder xxx
```

This can't be associated with certain objectives though.

**Comment by NeunEinser** [comment]
Oh, I only ever used Ctrl+F and searched for fake player :D
I would never have come up with that name

**Comment by NeunEinser** [comment]
Is there a strict lint option too?

**Comment by SPGoding** [comment]
It's also the name of the brigadier argument parser :eyes: [`minecraft:score_holder`](https://minecraft.gamepedia.com/Argument_types#minecraft:score_holder)

> Is there a strict lint option too?  
Yes.

**Comment by NeunEinser** [comment]
How is it called? Can't find anything with score in it on https://github.com/SPGoding/datapack-language-server/wiki/Lint-Rules

**Comment by NeunEinser** [comment]
Found it in the GUI, doesn't seem documented though
`"datapack.lint.strictScoreHolderCheck"`

**Comment by NeunEinser** [comment]
Should we leave this open for the per objective part? It's not super needed imo.

**Comment by SPGoding** [comment]
Yeah I think so too. And I updated the wiki, thanks!
