### ISSUE TITLE
In Tellraw JSON text, why can't the expected Boolean value of "bold" be enclosed in double quotes?

### ISSUE THREAD

**Issue by SNWCreations** [SPGoding/datapack-language-server#757]
Please look at the title first.
Is it possible to support double quoted Boolean values in later versions?
Although double quoted booleans work well in Minecraft, I hope to fix this problem.

**Comment by SPGoding** [comment]
TL;DR Nope.

The fact that Minecraft supports something weird for now doesn't make it necessary for DLS (or [minecraft-schemas](https://github.com/misode/minecraft-schemas), actually) not to warn it. It is generally bad practice to write boolean values in quotation marks, and the behavior of the game might change at any time in the future w/o notifications.

**Comment by SNWCreations** [comment]
(This is an unnecessary reply, so don't read it.)
Well, that's my habit. Maybe I'll think about getting rid of it later.
:)
