### ISSUE TITLE
Missing `executable` for /gamerule

### ISSUE THREAD

**Issue by YijunYuan** [SPGoding/datapack-language-server#97]
当在.mcfunction文件中写入
`gamerule maxCommandChainLength 2147483647`
时，插件提示该行出错：
![捕获](https://user-images.githubusercontent.com/7012463/68474510-8766d200-0260-11ea-82df-9d543a626bc9.PNG)

**Comment by SPGoding** [comment]
@all-contributors add YijunYuan for bug
